// Generated by gencpp from file turtle_patrol/PatrolRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_PATROL_MESSAGE_PATROLREQUEST_H
#define TURTLE_PATROL_MESSAGE_PATROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_patrol
{
template <class ContainerAllocator>
struct PatrolRequest_
{
  typedef PatrolRequest_<ContainerAllocator> Type;

  PatrolRequest_()
    : vel(0.0)
    , omega(0.0)  {
    }
  PatrolRequest_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , omega(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;

   typedef float _omega_type;
  _omega_type omega;





  typedef boost::shared_ptr< ::turtle_patrol::PatrolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_patrol::PatrolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolRequest_

typedef ::turtle_patrol::PatrolRequest_<std::allocator<void> > PatrolRequest;

typedef boost::shared_ptr< ::turtle_patrol::PatrolRequest > PatrolRequestPtr;
typedef boost::shared_ptr< ::turtle_patrol::PatrolRequest const> PatrolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_patrol::PatrolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_patrol::PatrolRequest_<ContainerAllocator1> & lhs, const ::turtle_patrol::PatrolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vel == rhs.vel &&
    lhs.omega == rhs.omega;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_patrol::PatrolRequest_<ContainerAllocator1> & lhs, const ::turtle_patrol::PatrolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_patrol

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_patrol::PatrolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_patrol::PatrolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_patrol::PatrolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eabcf020b6514d3ff27102ac1d24cb0e";
  }

  static const char* value(const ::turtle_patrol::PatrolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeabcf020b6514d3fULL;
  static const uint64_t static_value2 = 0xf27102ac1d24cb0eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_patrol/PatrolRequest";
  }

  static const char* value(const ::turtle_patrol::PatrolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request message types\n"
"float32 vel\n"
"float32 omega\n"
;
  }

  static const char* value(const ::turtle_patrol::PatrolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_patrol::PatrolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_patrol::PatrolRequest_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "omega: ";
    Printer<float>::stream(s, indent + "  ", v.omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_PATROL_MESSAGE_PATROLREQUEST_H
